# Development image with SDK for hot reload
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine

# Install debugger for development
RUN apk add --no-cache curl bash unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app

EXPOSE 5000

# The source code will be mounted via volume, so no need to copy it here
CMD ["dotnet", "watch", "run", "--project", "monitoring/BBT.Workflow.Monitor.HttpApi.Host/BBT.Workflow.Monitor.HttpApi.Host.csproj", "--urls", "http://+:5000"]
