// Historical issue #933 PostgreSQL fixture. Test-only; new maintenance SQL is generated by wf indexes generate.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Data;
using BBT.Aether.MultiSchema;
using BBT.Workflow.Definitions;
using BBT.Workflow.Definitions.Schemas;
using BBT.Workflow.Security;

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Npgsql;

namespace BBT.Workflow.Schemas;

/// <summary>Explicit maintenance DDL and a read-only catalog. Never performs DDL on a query request.</summary>
public sealed class LegacyAttributeIndexFixture(
    IConfiguration configuration, IOptionsMonitor<AttributeIndexOptions> options,
    ICurrentSchema currentSchema, ISchemaNameFormatter schemaNameFormatter, IMemoryCache cache)
    : IAttributeIndexCatalog
{
    private string ConnectionString => configuration.GetConnectionString("Default")
        ?? throw new InvalidOperationException("ConnectionStrings:Default is required.");

    private NpgsqlConnection CreateConnection(bool maintenance = false)
    {
        var builder = new NpgsqlConnectionStringBuilder(maintenance
            ? configuration.GetConnectionString("AttributeIndexMaintenance") ?? ConnectionString
            : ConnectionString);
        if (maintenance)
        {
            // The advisory lock belongs to this physical session, not to a pooled logical connection.
            builder.Pooling = false;
            builder.Multiplexing = false;
        }
        return new NpgsqlConnection(builder.ConnectionString);
    }

    public Task<IReadOnlySet<string>> GetReadyAsync(string schema, CancellationToken cancellationToken = default)
        => new PostgresAttributeIndexService(configuration, options, currentSchema, schemaNameFormatter, cache)
            .GetReadyAsync(schema, cancellationToken);

    public async Task ReconcileAsync(string schema, SchemaFilterContext context, CancellationToken cancellationToken = default)
    {
        schema = new SyncSchemaValidator().ValidateSchemaSync(schemaNameFormatter.Format(schema));
        using var scope = currentSchema.Change(schema);
        await using var connection = CreateConnection(maintenance: true);
        await connection.OpenAsync(cancellationToken);
        await using (var command = new NpgsqlCommand("SELECT pg_try_advisory_lock(hashtextextended(@key, 0))", connection))
        {
            command.Parameters.AddWithValue("key", $"attribute-indexes:{schema}");
            if (await command.ExecuteScalarAsync(cancellationToken) is not true)
                throw new InvalidOperationException($"Attribute index maintenance is already running for '{schema}'.");
        }
        var definitions = AttributeIndexDefinition.From(context);
        // Closing this non-pooled connection releases the lock, including cancellation/failure paths.
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
        await ExecuteAsync(connection, transaction,
            $"SET LOCAL lock_timeout = '{Math.Max(1, 5)}s'", cancellationToken);
        await ExecuteAsync(connection, transaction, $"""
            CREATE TABLE IF NOT EXISTS "{schema}"."AttributeIndexCatalog" (
                "Key" text PRIMARY KEY, "ColumnName" text NOT NULL, "PgType" text NOT NULL,
                "Indexes" text[] NOT NULL, "Ready" boolean NOT NULL DEFAULT false);
            """, cancellationToken);

        // Take the table lock before validation to prevent a write between validation and generation.
        await ExecuteAsync(connection, transaction, $"LOCK TABLE \"{schema}\".\"InstancesData\" IN ACCESS EXCLUSIVE MODE", cancellationToken);
        var retired = new List<string>();
        await using (var command = new NpgsqlCommand($"SELECT \"ColumnName\" FROM \"{schema}\".\"AttributeIndexCatalog\" WHERE @retire AND NOT (\"Key\" = ANY(@keys)) AND \"Ready\"", connection, transaction))
        {
            command.Parameters.AddWithValue("retire", true);
            command.Parameters.AddWithValue("keys", definitions.Select(d => d.Key).ToArray());
            await using var reader = await command.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken)) retired.Add(reader.GetString(0));
        }
        foreach (var column in retired)
        {
            if (!System.Text.RegularExpressions.Regex.IsMatch(column, "^q_[a-f0-9]{24}$"))
                throw new InvalidOperationException("Invalid managed projection name in catalog.");
            // Retain old values but stop evaluating an obsolete cast on future writes. Otherwise a
            // number -> string schema change could make the retained numeric projection reject writes.
            await ExecuteAsync(connection, transaction, $"ALTER TABLE \"{schema}\".\"InstancesData\" ALTER COLUMN \"{column}\" DROP EXPRESSION IF EXISTS", cancellationToken);
            await ExecuteAsync(connection, transaction, $"UPDATE \"{schema}\".\"AttributeIndexCatalog\" SET \"Ready\" = false WHERE \"ColumnName\" = '{column}'", cancellationToken);
        }
        if (definitions.Any(d => d.StorageType == "timestamptz"))
            await ExecuteAsync(connection, transaction, TimestampFunction(schema), cancellationToken);
        if (context.Fields.Values.Any(m => m.Indexed && NeedsTrigram(m)))
            await ExecuteAsync(connection, transaction, "CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public", cancellationToken);

        var additions = new List<string>();
        var comments = new List<string>();
        foreach (var definition in definitions)
        {
            var metadata = context.GetFieldMetadata(definition.Path)!;
            var accessor = AttributeConditionBuilder.BuildJsonTextAccessor(definition.Path, "Data");
            var expression = definition.StorageType switch
            {
                "numeric" => $"{accessor}::numeric",
                "timestamptz" => $"\"{schema}\".q_iso_timestamp_v1({accessor})",
                _ => accessor
            };
            var marker = $"vnext-attribute-index:v1:latest:{definition.Path}:{definition.StorageType}";
            var existing = false;
            var generated = false;
            await using (var inspect = new NpgsqlCommand("""
                SELECT a.attgenerated = 's', col_description(t.oid, a.attnum)
                FROM pg_class t JOIN pg_namespace n ON n.oid = t.relnamespace
                JOIN pg_attribute a ON a.attrelid = t.oid
                WHERE n.nspname = @schema AND t.relname = 'InstancesData' AND a.attname = @column AND NOT a.attisdropped
                """, connection, transaction))
            {
                inspect.Parameters.AddWithValue("schema", schema);
                inspect.Parameters.AddWithValue("column", definition.ColumnName);
                await using var reader = await inspect.ExecuteReaderAsync(cancellationToken);
                if (await reader.ReadAsync(cancellationToken))
                {
                    existing = true; generated = reader.GetBoolean(0);
                    if (reader.IsDBNull(1) || reader.GetString(1) != marker)
                        throw new InvalidOperationException($"Projection name collision for '{schema}:{definition.Path}'.");
                }
            }
            // COUNT(expression) forces evaluation of every historical row as well as latest rows.
            try
            {
                await ExecuteAsync(connection, transaction, $"SELECT COUNT({expression}) FROM \"{schema}\".\"InstancesData\"", cancellationToken);
            }
            catch (PostgresException ex)
            {
                throw new InvalidOperationException($"Cannot index '{schema}:{definition.Path}' as {definition.StorageType}: existing data failed conversion. No projections activated.", ex);
            }
            if (existing && !generated)
                await ExecuteAsync(connection, transaction, $"ALTER TABLE \"{schema}\".\"InstancesData\" DROP COLUMN \"{definition.ColumnName}\"", cancellationToken);
            if (!existing || !generated)
                additions.Add($"ADD COLUMN \"{definition.ColumnName}\" {definition.StorageType} GENERATED ALWAYS AS (CASE WHEN \"IsLatest\" THEN {expression} END) STORED");
            comments.Add($"COMMENT ON COLUMN \"{schema}\".\"InstancesData\".\"{definition.ColumnName}\" IS '{InputValidator.EscapePostgresSingleQuotedString(marker)}'");
        }
        // PostgreSQL rewrites the table once for all newly requested stored projections.
        if (additions.Count > 0)
            await ExecuteAsync(connection, transaction, $"ALTER TABLE \"{schema}\".\"InstancesData\" {string.Join(", ", additions)}", cancellationToken);
        foreach (var comment in comments) await ExecuteAsync(connection, transaction, comment, cancellationToken);
        foreach (var definition in definitions)
        {
            var metadata = context.GetFieldMetadata(definition.Path)!;
            var indexes = new List<string> { $"ix_{definition.Key}_btree_v2" };
            var keys = definition.StorageType == "text"
                ? $"(\"{definition.ColumnName}\", \"InstanceId\")"
                : $"(\"{definition.ColumnName}\") INCLUDE (\"InstanceId\")";
            await ExecuteAsync(connection, transaction, $"""
                CREATE INDEX IF NOT EXISTS "{indexes[0]}" ON "{schema}"."InstancesData"
                {keys} WHERE "IsLatest" = true
                """, cancellationToken);
            if (definition.StorageType == "text" && metadata.Sortable)
            {
                var descending = $"ix_{definition.Key}_desc_v2";
                indexes.Add(descending);
                await ExecuteAsync(connection, transaction, $"""
                    CREATE INDEX IF NOT EXISTS "{descending}" ON "{schema}"."InstancesData"
                    ("{definition.ColumnName}" DESC, "InstanceId" ASC) WHERE "IsLatest" = true
                    """, cancellationToken);
            }
            if (definition.StorageType == "text" && NeedsTrigram(metadata))
            {
                var trigram = $"ix_{definition.Key}_trgm";
                indexes.Add(trigram);
                await ExecuteAsync(connection, transaction, $"""
                    CREATE INDEX IF NOT EXISTS "{trigram}" ON "{schema}"."InstancesData" USING gin
                    ("{definition.ColumnName}" COLLATE "tr-TR-x-icu" public.gin_trgm_ops) WHERE "IsLatest" = true
                    """, cancellationToken);
            }
            await using var register = new NpgsqlCommand($"""
                INSERT INTO "{schema}"."AttributeIndexCatalog" ("Key", "ColumnName", "PgType", "Indexes", "Ready")
                VALUES (@key, @column, @type, @indexes, true)
                ON CONFLICT ("Key") DO UPDATE SET "Indexes" = EXCLUDED."Indexes", "Ready" = true
                """, connection, transaction);
            register.Parameters.AddWithValue("key", definition.Key);
            register.Parameters.AddWithValue("column", definition.ColumnName);
            register.Parameters.AddWithValue("type", definition.StorageType == "timestamptz" ? "timestamp with time zone" : definition.StorageType);
            register.Parameters.AddWithValue("indexes", indexes.ToArray());
            await register.ExecuteNonQueryAsync(cancellationToken);
        }
        await ExecuteAsync(connection, transaction, $"ANALYZE \"{schema}\".\"InstancesData\"", cancellationToken);
        await transaction.CommitAsync(cancellationToken);
        cache.Remove((typeof(PostgresAttributeIndexService), ConnectionString, schema));

    }

    private static bool NeedsTrigram(SchemaFieldMetadata metadata) => metadata.FilterOperators.Any(
        op => op.Equals("contains", StringComparison.OrdinalIgnoreCase) ||
              op.Equals("startsWith", StringComparison.OrdinalIgnoreCase) || op.Equals("endsWith", StringComparison.OrdinalIgnoreCase));

    private async Task ExecuteAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, string sql, CancellationToken ct)
    {
        await using var command = new NpgsqlCommand(sql, connection, transaction);
        command.CommandTimeout = Math.Max(1, 3600);
        await command.ExecuteNonQueryAsync(ct);
    }

    // Parse numeric components and offsets explicitly. No DateStyle/TimeZone-sensitive text cast,
    // named time zones, relative dates, infinity, or locale-sensitive date input is accepted.
    internal static string TimestampFunction(string schema) => $$"""
        CREATE OR REPLACE FUNCTION "{{schema}}".q_iso_timestamp_v1(value text)
        RETURNS timestamptz LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE AS $function$
        DECLARE m text[]; local_value timestamp; offset_minutes integer := 0;
        BEGIN
          m := regexp_match(value, '^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2}(\.[0-9]+)?)(Z|([+-])([0-9]{2}):([0-9]{2}))$');
          IF m IS NULL THEN RAISE EXCEPTION 'Expected ISO-8601 date-time with explicit offset' USING ERRCODE = '22007'; END IF;
          IF m[4]::int > 23 OR m[5]::int > 59 OR m[6]::numeric >= 60
             OR COALESCE(m[10]::int, 0) > 15 OR COALESCE(m[11]::int, 0) > 59 THEN
            RAISE EXCEPTION 'Invalid ISO-8601 time or offset' USING ERRCODE = '22007';
          END IF;
          local_value := make_timestamp(m[1]::int, m[2]::int, m[3]::int, m[4]::int, m[5]::int, m[6]::double precision);
          IF m[8] <> 'Z' THEN
            offset_minutes := (m[10]::int * 60 + m[11]::int) * CASE WHEN m[9] = '-' THEN -1 ELSE 1 END;
          END IF;
          RETURN (local_value - make_interval(mins => offset_minutes)) AT TIME ZONE 'UTC';
        END;
        $function$;
        """;
}
