namespace BBT.Workflow.Authorization;

/// <summary>
/// Host-level configuration for master-schema <c>x-encryption</c> (<c>hash</c> and <c>encrypt</c>, both applied when
/// instance data is written).
/// <para>
/// <b>No key or salt is configuration.</b> Each instance gets its own AES-256 key and hash salt, generated by the runtime
/// on the instance's first protected write and stored in its flow schema's <c>InstanceSecrets</c> table (committee
/// decision, 2026-09-30). The runtime never serves them; it caches them only in its own process (L1) — never in Redis.
/// </para>
/// </summary>
public sealed class SchemaEncryptionOptions
{
    /// <summary>Configuration section name.</summary>
    public const string SectionName = "SchemaEncryption";

    /// <summary>
    /// Whether new writes hash the <c>hash</c> paths and encrypt the <c>encrypt</c> paths. Default true. The operational
    /// rollback switch: false stores new values in plaintext while existing tokens keep decrypting (their secrets stay in
    /// the table). While it is false a schema declaring <c>hash</c> or <c>encrypt</c> cannot be published. Decryption and
    /// the value served to callers outside the exemption list can never be switched off.
    /// </summary>
    public bool EncryptWrites { get; set; } = true;

    /// <summary>Maximum number of instance secrets held in the in-process cache. Default 100 000.</summary>
    public int SecretCacheEntries { get; set; } = 100_000;

    /// <summary>Sliding expiry of a cached instance secret, in minutes. Default 30.</summary>
    public int SecretCacheSlidingMinutes { get; set; } = 30;
}

/// <summary>Default <see cref="IFieldEncryptionStatus"/>: the runtime can always create secrets, so only the switch decides.</summary>
public sealed class FieldEncryptionStatus(Microsoft.Extensions.Options.IOptions<SchemaEncryptionOptions> options) : IFieldEncryptionStatus
{
    /// <inheritdoc />
    public bool CanEncrypt => options.Value.EncryptWrites;
}
