<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BBT.Workflow.Monitor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Api" Version="$(OpenTelemetryPackageVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../aether/framework/src/BBT.Aether.Application/BBT.Aether.Application.csproj" />
    <ProjectReference Include="..\..\src\BBT.Workflow.Domain\BBT.Workflow.Domain.csproj" />
    <ProjectReference Include="..\..\src\BBT.Workflow.Application\BBT.Workflow.Application.csproj" />
  </ItemGroup>
</Project>