// <auto-generated />
using System;
using System.Collections.Generic;
using BBT.Workflow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BBT.Workflow.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20250911201509_Instance_AddMetaData")]
    partial class Instance_AddMetaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BBT.Workflow.Instances.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Instances", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("InstanceActions", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceCorrelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubFlowDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SubFlowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubFlowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubFlowType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasComment("SubFlow Type: S (SubFlow - blocking) or P (SubProcess - non-blocking)");

                    b.Property<string>("SubFlowVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ParentInstanceId", "IsCompleted", "SubFlowType")
                        .HasDatabaseName("IX_InstancesCorrelations_Performance");

                    b.ToTable("InstancesCorrelations", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Version")
                        .IsUnique();

                    b.ToTable("InstancesData", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExpressionValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("InstanceJobs", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("FaultedTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FaultedTaskId");

                    b.HasIndex("TransitionId");

                    b.ToTable("InstanceTasks", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("InstanceTransitions", "public");
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceAction", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.InstanceTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Detail", b1 =>
                        {
                            b1.Property<Guid>("InstanceActionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Detail");

                            b1.HasKey("InstanceActionId");

                            b1.ToTable("InstanceActions", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceActionId");
                        });

                    b.Navigation("Detail")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceCorrelation", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany("ChildCorrelations")
                        .HasForeignKey("ParentInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceData", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany("DataList")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Data", b1 =>
                        {
                            b1.Property<Guid>("InstanceDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Data");

                            b1.HasKey("InstanceDataId");

                            b1.ToTable("InstancesData", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceDataId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceJob", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Payload", b1 =>
                        {
                            b1.Property<Guid>("InstanceJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Payload");

                            b1.HasKey("InstanceJobId");

                            b1.ToTable("InstanceJobs", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceJobId");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTask", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.InstanceTask", null)
                        .WithMany()
                        .HasForeignKey("FaultedTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BBT.Workflow.Instances.InstanceTransition", null)
                        .WithMany()
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Request", b1 =>
                        {
                            b1.Property<Guid>("InstanceTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Request");

                            b1.HasKey("InstanceTaskId");

                            b1.ToTable("InstanceTasks", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTaskId");
                        });

                    b.OwnsOne("BBT.Workflow.JsonData", "Response", b1 =>
                        {
                            b1.Property<Guid>("InstanceTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Response");

                            b1.HasKey("InstanceTaskId");

                            b1.ToTable("InstanceTasks", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTaskId");
                        });

                    b.Navigation("Request")
                        .IsRequired();

                    b.Navigation("Response")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTransition", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Body", b1 =>
                        {
                            b1.Property<Guid>("InstanceTransitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Body");

                            b1.HasKey("InstanceTransitionId");

                            b1.ToTable("InstanceTransitions", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTransitionId");
                        });

                    b.OwnsOne("BBT.Workflow.JsonData", "Header", b1 =>
                        {
                            b1.Property<Guid>("InstanceTransitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Header");

                            b1.HasKey("InstanceTransitionId");

                            b1.ToTable("InstanceTransitions", "public");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTransitionId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Header")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.Instance", b =>
                {
                    b.Navigation("ChildCorrelations");

                    b.Navigation("DataList");
                });
#pragma warning restore 612, 618
        }
    }
}
