// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using BBT.Workflow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BBT.Workflow.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260409000000_FixSubFlowStateChangedAtTimezone")]
    partial class FixSubFlowStateChangedAtTimezone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BBT.Aether.Domain.Entities.BackgroundJobInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByBehalfOf")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CreatedByBehalfOf");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("ExpressionValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime?>("HandledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByBehalfOf")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ModifiedByBehalfOf");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobName")
                        .HasDatabaseName("IX_BackgroundJobs_JobName");

                    b.HasIndex("HandlerName", "Status")
                        .HasDatabaseName("IX_BackgroundJobs_HandlerName_Status");

                    b.HasIndex("Status", "HandledTime")
                        .HasDatabaseName("IX_BackgroundJobs_Processing");

                    b.ToTable("BackgroundJobs", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByBehalfOf")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CreatedByBehalfOf");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("EffectiveState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EffectiveStateSubType")
                        .HasColumnType("integer");

                    b.Property<int?>("EffectiveStateType")
                        .HasColumnType("integer");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FlowVersion")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByBehalfOf")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ModifiedByBehalfOf");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveState")
                        .HasDatabaseName("IX_Instances_EffectiveState");

                    b.ToTable("Instances", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("InstanceActions", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceCorrelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParentInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubFlowCurrentState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubFlowDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SubFlowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubFlowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SubFlowStateChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubFlowType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasComment("SubFlow Type: S (SubFlow - blocking) or P (SubProcess - non-blocking)");

                    b.Property<string>("SubFlowVersion")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("ParentInstanceId", "IsCompleted", "SubFlowType")
                        .HasDatabaseName("IX_InstancesCorrelations_Performance");

                    b.ToTable("InstancesCorrelations", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("99914b932bd37a50b983c5e7c90ae93b");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HistorySequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLatest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("InstanceId")
                        .IsUnique()
                        .HasDatabaseName("UX_InstancesData_Instance_IsLatest")
                        .HasFilter("\"IsLatest\" = true");

                    b.HasIndex("InstanceId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_InstancesData_Instance_VersionNo");

                    b.ToTable("InstancesData", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("InstanceJobs", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BusinessStatus")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("FaultedTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FaultedTaskId");

                    b.HasIndex("TransitionId");

                    b.ToTable("InstanceTasks", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByBehalfOf")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("CreatedByBehalfOf");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TriggerType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("InstanceTransitions", (string)null);
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceAction", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.InstanceTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Detail", b1 =>
                        {
                            b1.Property<Guid>("InstanceActionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Detail");

                            b1.HasKey("InstanceActionId");

                            b1.ToTable("InstanceActions");

                            b1.WithOwner()
                                .HasForeignKey("InstanceActionId");
                        });

                    b.Navigation("Detail")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceCorrelation", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany("ActiveCorrelations")
                        .HasForeignKey("InstanceId");

                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany("ChildCorrelations")
                        .HasForeignKey("ParentInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceData", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany("DataList")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Data", b1 =>
                        {
                            b1.Property<Guid>("InstanceDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Data");

                            b1.HasKey("InstanceDataId");

                            b1.ToTable("InstancesData");

                            b1.WithOwner()
                                .HasForeignKey("InstanceDataId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTask", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.InstanceTask", null)
                        .WithMany()
                        .HasForeignKey("FaultedTaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BBT.Workflow.Instances.InstanceTransition", null)
                        .WithMany()
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "InvocationResult", b1 =>
                        {
                            b1.Property<Guid>("InstanceTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("InvocationResult");

                            b1.HasKey("InstanceTaskId");

                            b1.ToTable("InstanceTasks");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTaskId");
                        });

                    b.OwnsOne("BBT.Workflow.JsonData", "Request", b1 =>
                        {
                            b1.Property<Guid>("InstanceTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Request");

                            b1.HasKey("InstanceTaskId");

                            b1.ToTable("InstanceTasks");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTaskId");
                        });

                    b.OwnsOne("BBT.Workflow.JsonData", "Response", b1 =>
                        {
                            b1.Property<Guid>("InstanceTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Response");

                            b1.HasKey("InstanceTaskId");

                            b1.ToTable("InstanceTasks");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTaskId");
                        });

                    b.Navigation("InvocationResult")
                        .IsRequired();

                    b.Navigation("Request")
                        .IsRequired();

                    b.Navigation("Response")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.InstanceTransition", b =>
                {
                    b.HasOne("BBT.Workflow.Instances.Instance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBT.Workflow.JsonData", "Body", b1 =>
                        {
                            b1.Property<Guid>("InstanceTransitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Body");

                            b1.HasKey("InstanceTransitionId");

                            b1.ToTable("InstanceTransitions");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTransitionId");
                        });

                    b.OwnsOne("BBT.Workflow.JsonData", "Header", b1 =>
                        {
                            b1.Property<Guid>("InstanceTransitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Header");

                            b1.HasKey("InstanceTransitionId");

                            b1.ToTable("InstanceTransitions");

                            b1.WithOwner()
                                .HasForeignKey("InstanceTransitionId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Header")
                        .IsRequired();
                });

            modelBuilder.Entity("BBT.Workflow.Instances.Instance", b =>
                {
                    b.Navigation("ActiveCorrelations");

                    b.Navigation("ChildCorrelations");

                    b.Navigation("DataList");
                });
#pragma warning restore 612, 618
        }
    }
}
